Shorten assertion check text
This is to avoid situations where the stdout is split across multiple lines (e.g. when this test is run in GitHub Actions) and the full text of the warning message is not contiguous.

To clarify, here is how the pervious version of this test was failing in GHA:

AssertionError: assert 'No schema URL provided, skipping KEV JSON validation' in '[19:05:08] WARNING  No schema URL provided, skipping KEV JSON         main.py:46\n                    validation.                                                 \nProcessing KEV feed ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00\nDeleting KEV docs ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   \n'

Update cyhy-config dependency to version 1

Remove unnecessary dependency pins